name: Build and Deploy Zensical

on:
  push:
    branches:
      - main
      - target-alignment

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install zensical

      - run: zensical build --clean

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
